version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql-laravel
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ca_canh_laravel
            MYSQL_USER: thoipham
            MYSQL_PASSWORD: cacanh@123
        ports:
            - "3307:3306"
        command:
            [
                "--default-authentication-plugin=mysql_native_password",
                "--skip-ssl",
                "--require_secure_transport=OFF",
            ]
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    db_data:
